/// Flutter icons Plus_circle
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Plus_circle
///      fonts:
///       - asset: fonts/Plus_circle.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Plus_circle {
  Plus_circle._();

  static const _kFontFam = 'Plus_circle';
  static const _kFontPkg = null;

  static const IconData gplus_circled =
      IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
